{% set name = "versioneer" %}
{% set version = "0.28" %}
{% set sha256 = "7175ca8e7bb4dd0e3c9779dd2745e5b4a6036304af3f5e50bd896f10196586d6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [py<37]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - versioneer = versioneer:main

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
    - tomli 2.0.1  # [py<311]
  run:
    - python

test:
  imports:
    - versioneer
  requires:
    - pip
  commands:
    - pip check
    - {{ SP_DIR }}/versioneer version

about:
  home: https://github.com/python-versioneer/python-versioneer
  license: Unlicense
  license_file: LICENSE
  license_family: None
  summary: Easy VCS-based management of project version strings
  description: |
    This is a tool for managing a recorded version number
    in setuptools-based python projects.
  dev_url: https://github.com/python-versioneer/python-versioneer/blob/master/pyproject.toml
  doc_url: https://github.com/python-versioneer/python-versioneer/blob/master/pyproject.toml

extra:
  recipe-maintainers:
    - jakirkham
