{% set name = "versioneer" %}
{% set version = "0.18" %}
{% set sha256 = "ead1f78168150011189521b479d3a0dd2f55c94f5b07747b484fd693c3fbf335" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - versioneer = versioneer:main

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  commands:
    - versioneer version

about:
  home: https://github.com/warner/python-versioneer
  license: Public Domain
  summary: Easy VCS-based management of project version strings

extra:
  recipe-maintainers:
    - jakirkham
