{% set name = "versioneer" %}
{% set version = "0.22" %}
{% set sha256 = "9f0e9a2cb5ef521cbfd104d43a208dd9124dfb4accfa72d694e0d0430a0142bc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - versioneer = versioneer:main

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6

test:
  commands:
    - versioneer version

about:
  home: https://github.com/python-versioneer/python-versioneer
  license: LicenseRef-Public-Domain
  summary: Easy VCS-based management of project version strings

extra:
  recipe-maintainers:
    - jakirkham
