{% set name = "versioneer" %}
{% set version = "0.26" %}
{% set sha256 = "84fc729aa296d1d26645a8f62f178019885ff6f9a1073b29a4a228270ac5257b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - versioneer = versioneer:main

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - python >=3.6

test:
  requires:
    - pip
  commands:
    - pip check
    - versioneer version

about:
  home: https://github.com/python-versioneer/python-versioneer
  license: Unlicense
  license_file: LICENSE
  summary: Easy VCS-based management of project version strings

extra:
  recipe-maintainers:
    - jakirkham
