travis:
  secure:
    BINSTAR_TOKEN: uk/jGpUNDerCoYZPNlw9gsb7PLDcYHg3CTXWBtFe7LOlscONb5T3AfS9jH58RmaTDZ4mbfZIXLeW1m3NigA5n1GN8chd1LECIcYBOfPE8ypJp80vYvEPAsi1nPXzvxzNtENr75udYc3d05Ef57BKdd0bh4nkqcov7zw6X6M5jvSnwa2xPs4vR/3Fmp0bFtiqYsHK8MQxI3rXGEWb1vcXICM9X8wNsuxs4zbTQxDxxu+2J5ilcUmA18e7qFTWiMjRhPtN6Ta4Nnv73w+4/iFAQHTxYo1aHRhLuZ/0lLnc/OFYXVO0KtKKnAN6ltyd6Tr9LIJF905M0A7CqWxLxbqjiiXI7vpuaXZI9yralsSq7vnFg1GYJ8TDI9HrrAscoMiG2rdxsmhhDZqt6hCCktNPHxUJpmX6/mQwM7rKhwzrnWo/S3sCMK2ZFFve8FhkD4nNURhRmIwdQV3xQOcREI6UnJavZrVMamWugW7ycUAR7A2AWDm6le471Z+VcAcDlUEiW+blS3i6nduJ6/1XHt79yx0wyZp/ImfmiZU+dZNRnNyK4T7E+GFK5Py0+PzP/7Bguyk/djjuLoHxI9pnJdED4+SonWR32uSkzK/GxCckLQYbNsnYGYnGDCyqaJSXeB0CBJwr22gAqHn+6JpYuwIW3mJ8UqrVcu4OuSH+ipuUnuQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
