travis:
  secure:
    BINSTAR_TOKEN: MMYu09I7wNbhCD1ZmbfxmoH2L3Xt3k7qu05a4OJpQIyZ/XYFG3TdXv0devWT186ZCy4yDfa3oijO0CfnLc+BdA7RxqmyX4Iaubuo3awRuN1tQf/W8rsp5FlFFw9xn14ep5sbJ9Nd5Y92W9t//YSx5YOl/zrrTXDRANui0pKEi44XLtBxDdQQioo4V5/orjXWnecAATN8Qr3holTs0RgDgxcFZPMGTAluSFV4CEOOej5qZEPdG4Ul9+uuilannzV8n7v2+F9vgKPpVyp/R7rEQpCeubST4Agzb35wjfuyEzcs7Rw40kjlS67aElpsDleaDzCgcG63bB+XSLSDP1kdv9L3vYx1ljfbcyczXNQXdgIYGIvb4cBkHIxVz9oKTL/s0gW8LLCvB7pOgnbDnww0eYsh/X5guNw7cQDBNKDXsWTlQq1/TCwCzix6Wk8Wbhu2I8XuP4iWaNrdMRRWrYPQAIDXPxF+INDt84bFrrpMzXz90wpO4LjkO7Yfkkmwhg8hOym53dxbLP+NpW7kppBXVfuC6Vx1wFfVV80IwqqYu8L0uT/lN6iRjDkwE5WbGF14inSYyKkZQ5j2zYSIKFtlzrIZYoC2G+dmL5oqR+AqTXTZ7nA6qDqid+WnNssSu+PWv/RRtKYAEtqUWuIaWwHM9dY+1WXs5qkeK2JxHH6RN8U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
